version: "3.8"

services:
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_DB: "wb-l0"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5433:5432"

  nats-stream:
    image: nats-streaming
    restart: always
    ports:
      - "8222:8222"
      - "4222:4222"

